# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xenon\PycharmProjects\music\myui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 523)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 523))
        MainWindow.setMaximumSize(QtCore.QSize(600, 523))
        MainWindow.setWindowTitle("Musical Player Project")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/other/BlackIcons/electronic-music (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.label_Track = QtWidgets.QLabel(self.centralwidget)
        self.label_Track.setGeometry(QtCore.QRect(150, 320, 291, 20))
        self.label_Track.setStyleSheet("font: 16pt \"Candara\";\n"
"")
        self.label_Track.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_Track.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Track.setTextFormat(QtCore.Qt.PlainText)
        self.label_Track.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Track.setObjectName("label_Track")
        self.label_Artist = QtWidgets.QLabel(self.centralwidget)
        self.label_Artist.setGeometry(QtCore.QRect(150, 350, 291, 20))
        self.label_Artist.setStyleSheet("font: 14pt \"Candara Light\";")
        self.label_Artist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Artist.setObjectName("label_Artist")
        self.pushButton_Album = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Album.setGeometry(QtCore.QRect(140, 10, 300, 300))
        self.pushButton_Album.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/othericons/album.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Album.setIcon(icon1)
        self.pushButton_Album.setIconSize(QtCore.QSize(300, 300))
        self.pushButton_Album.setFlat(True)
        self.pushButton_Album.setObjectName("pushButton_Album")
        self.pushButton_Load_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Load_folder.setGeometry(QtCore.QRect(11, 26, 52, 48))
        self.pushButton_Load_folder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/other/provodnik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Load_folder.setIcon(icon2)
        self.pushButton_Load_folder.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Load_folder.setFlat(True)
        self.pushButton_Load_folder.setObjectName("pushButton_Load_folder")
        self.pushButton_Prev = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Prev.setGeometry(QtCore.QRect(49, 430, 62, 58))
        self.pushButton_Prev.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Prev.setIcon(icon3)
        self.pushButton_Prev.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Prev.setFlat(True)
        self.pushButton_Prev.setObjectName("pushButton_Prev")
        self.pushButton_Play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Play.setEnabled(True)
        self.pushButton_Play.setGeometry(QtCore.QRect(271, 430, 62, 58))
        self.pushButton_Play.setAcceptDrops(False)
        self.pushButton_Play.setToolTip("")
        self.pushButton_Play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Play.setIcon(icon4)
        self.pushButton_Play.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Play.setFlat(True)
        self.pushButton_Play.setObjectName("pushButton_Play")
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(493, 430, 62, 58))
        self.pushButton_Next.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/fast-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/fast-forward.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.pushButton_Next.setIcon(icon5)
        self.pushButton_Next.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Next.setAutoDefault(False)
        self.pushButton_Next.setDefault(False)
        self.pushButton_Next.setFlat(True)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.pushButton_Volume_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Volume_plus.setGeometry(QtCore.QRect(530, 90, 52, 48))
        self.pushButton_Volume_plus.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/high-volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Volume_plus.setIcon(icon6)
        self.pushButton_Volume_plus.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Volume_plus.setAutoDefault(False)
        self.pushButton_Volume_plus.setDefault(False)
        self.pushButton_Volume_plus.setFlat(True)
        self.pushButton_Volume_plus.setObjectName("pushButton_Volume_plus")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(104, 401, 391, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setMouseTracking(True)
        self.horizontalSlider.setTabletTracking(True)
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.horizontalSlider.setAcceptDrops(False)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setStyleSheet("\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(3)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 401, 31, 16))
        self.label_2.setStyleSheet("font: 25 12pt \"Bahnschrift Light Condensed\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(61, 401, 47, 16))
        self.label_3.setStyleSheet("font: 25 12pt \"Bahnschrift Light Condensed\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_Pause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Pause.setGeometry(QtCore.QRect(382, 430, 62, 58))
        self.pushButton_Pause.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Pause.setIcon(icon7)
        self.pushButton_Pause.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Pause.setFlat(True)
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(160, 430, 62, 58))
        self.pushButton_Stop.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/icons8-stop-filled-50 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Stop.setIcon(icon8)
        self.pushButton_Stop.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Stop.setFlat(True)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_Load_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Load_file.setGeometry(QtCore.QRect(11, 85, 52, 48))
        self.pushButton_Load_file.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/audio-file-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Load_file.setIcon(icon9)
        self.pushButton_Load_file.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Load_file.setFlat(True)
        self.pushButton_Load_file.setObjectName("pushButton_Load_file")
        self.pushButton_Volume_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Volume_minus.setGeometry(QtCore.QRect(530, 36, 52, 48))
        self.pushButton_Volume_minus.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/MusicPlayerDark/BlackIcons/low-volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Volume_minus.setIcon(icon10)
        self.pushButton_Volume_minus.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Volume_minus.setFlat(True)
        self.pushButton_Volume_minus.setObjectName("pushButton_Volume_minus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_Track.setText(_translate("MainWindow", "Track name"))
        self.label_Artist.setText(_translate("MainWindow", "Artist name"))
        self.pushButton_Load_folder.setToolTip(_translate("MainWindow", "Выберите папку с музыкой"))
        self.label_2.setText(_translate("MainWindow", "00:00"))
        self.label_3.setText(_translate("MainWindow", "00:00"))

import recources_rc
#import icons1_rc_rc
